config/routes.rb
Lawdingo::Application.routes.draw do
  
  resources :appointments, :only => [:create]
  resources :clients, :only => [:new, :create] do
    post '/new', :on => :collection
  end

  namespace :framey do
    resources :videos
  end
  post "framey/callback" => "framey/videos#callback"

  match '/attorneys/:id/*slug' => redirect{|params| "/lawyers/#{params[:id]}/#{params[:slug]}"}
  match '/attorney-directory/:page' => redirect{|params| "/lawyers/directory/#{params[:page]}"}
  match '/attorney-directory', :to => redirect('/lawyers/directory')

  match '/lawyers/:service_type(/:state)' => 'users#home', :as => :state, :defaults => { :service_type => 'Legal-Advice'}, :constraints => {:service_type => /Legal-Advice|Legal-Services/}
  match '/lawyers/:service_type/:state(/:practice_area)' => 'users#home', :constraints => {:service_type => /Legal-Advice|Legal-Services/}
  match '/lawyers/:service_type/:state/:practice_area(/:practice_subarea)' => 'users#home', :as => :filtered, :defaults => { :service_type => 'Legal-Advice', :state => 'All-States', :practice_area => 'All' }, :constraints => {:service_type => /Legal-Advice|Legal-Services/}
  resources :lawyers, :only => [:new, :show, :create, :update], :constraints => {:id => /([0-9])+/} do
    get '/directory(/:page)', :action => :directory, :on => :collection, :as => :directory, :constraints => {:page => /([0-9])+/}
    member do
      get :states
      get :practice_areas
      match '/call-payment(/:type)', :action => :call_payment, :as => :call_payment
    end
    resources :questions, :only => [:index]
  end
  get '/lawyers/:id(/*slug)' => "lawyers#show", :constraints => {:id => /([0-9])+/}, :as => :lawyer
  
  resources :questions, :only=>[:show] do
    resources :answers, :only=>[:new]
  end

  match '/apply(/:id)' => "lawyers#new", :as => :new_lawyer
  
  match '/contact' => "contact#index", :as => :contact
  post '/contact/send_email' => "contact#send_email", :as => :send_email
  post '/contact/new_subscriber' => "contact#new_subscriber", :as => :new_subscriber

  post '/flash/notice' => "flash#notice", :as => :notice
  post '/flash/alert' => "flash#alert", :as => :alert
  
  resources :answers
  resources :questions, :only => [:create, :update] do 
    member do
      get :options, :as => :question_options
    end
  end
  resources :reviews
  resources :schools
  resources :inquiries, only: :show
  resources :bids, only: :create
  get "password_resets/new"

  match '/paid' => "stripes#new", :as => :subscribe_lawyer
  resource :stripe, only: [:new, :create] do
    post :coupon_validate
    get '/subscribe_question/:question_id', :action => :subscribe_question, :as => :subscribe_question
    post :subscribe_question_create, :on => :collection
  end

  resources :users do
    resources :daily_hours, :only => [:index] do
      collection do
        put "update"
      end
    end

    resources :offerings, shallow: true

    put "update_card_details"
    put 'image_upload'
    get 'chat_session'
    get 'onlinestatus'
  end

  resources :sessions
  resources :password_resets
  resources :conversations do
    get 'review'
    get 'summary'
  end
  match 'conversations/:conversation_id/summary(/:form)' => "conversations#summary", as: :conversation_summary

  namespace :admin do
    resources :questions, only: [:index, :show] do
      post "send_inquiry", on: :collection
    end
    resources :clients
    resources :lawyers do
      get 'account_approval'
      get 'hm_image'
    end
    resources :clsessions
    resources :pages
    resources :homepage_images
    resources :practice_areas
  end

  resources :messages do
    collection do
      get :clear_session_message
      post '/send_message/:lawyer_id', :action => :send_message_to_lawyer, :as => :schedule_session
    end
  end  

  match 'modparam' =>'users#update_parameter', :as =>:update_parameter
  match "/users/create_lawyer_request", to: "users#create_lawyer_request", as: :create_lawyer_request
  match '/user/sessions/:user_id' =>"users#session_history", :as =>:user_session_history
  match '/users/:user_id/daily_hours' =>"users#daily_hours", :as =>:user_daily_hours
  
  
  match '/users/:user_id' =>"users#account_information", :as =>:user_account_information
  match '/about' =>"pages#show", :name =>'about', :as =>:about_page
  match '/about_attorneys' =>"pages#about_attorneys", :name =>'about_attorneys', :as =>:about_attorneys
  match '/terms' =>"pages#terms_of_use", :name =>'terms', :as =>:terms_page  
  match '/login' => "sessions#new", :as => :login
  match '/logout' => "sessions#destroy", :as => :logout
  match '/details' => 'users#payment_info', :as => :card_detail
  match '/welcome' => 'users#welcome_lawyer', :as => :welcome
  match '/Register' => 'users#register_for_videochat', :as => :register_videochat
  match '/find_friend' => 'users#find_remote_user_for_videochat', :as => :find_remote_user
  match '/UpdateBusyStatus' => 'users#update_busy_status', :as => :UpdateBusyStatus
  match '/UpdateOnlineStatus' => 'users#update_online_status', :as => :UpdateOnlineStatus
  match '/twilio/phonecall' => 'users#start_phone_call', :as => :phonecall
  match '/twilio/createcall' => 'users#create_phone_call', :as => :create_call
  match '/updatePaymentInfo' => 'users#update_payment_info'
  match '/CheckPaymentInfo' => 'users#has_payment_info'
  match '/CheckCallStatus' => 'users#check_call_status'
  match '/UpdateCallStatus' => 'users#update_call_status'
  match '/haveIPaymentInfo' => 'users#have_i_payment_info'

  match "/twilio/welcome", to: "twilio#welcome", as: :twilio_welcome
  match "/twilio/dial-lawyer", to: "twilio#dial_lawyer", as: :twilio_dial_lawyer
  match "/twilio/goodbye", to: "twilio#goodbye", as: :twilio_goodbye
  match "/twilio/callback", to: "twilio#callback", as: :twilio_callback
  match "/twilio/fallback", to: "twilio#fallback", as: :twilio_fallback
  match "/twilio/conference", to: "twilio#connect_to_conference", as: :twilio_conference
  match "/twilio/hangup", to: "twilio#hangup", as: :twilio_hangup
  match "/twilio/check-call-status", to: "twilio#check_call_status", as: :twilio_check_call_status
  match "/twilio/update-call-status", to: "twilio#update_call_status", as: :twilio_update_call_status

  match '/admin' =>"users#show", :as =>:admin_home
  match '/auto-detect/detect-state' => 'users#detect_state'
  match '/lawyers' => 'users#home'

  root :to => 'users#landing_page'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

  match '/LoginByApp' => 'sessions#login_by_app'
  match '/UpdateOnlineByApp' => 'sessions#set_status_by_app'
  
end

app/controllers/stripes_controller.rb
class StripesController < ApplicationController

	before_filter :authenticate
	before_filter :check_lawyer_access, :only => [:new, :create, :coupon_validate]
  before_filter :check_client_access, :only => [:subscribe_question, :subscribe_question_create]
  
	def new
		@lawyer.create_stripe_customer! unless @lawyer.stripe_customer_token
	end

	def create
		respond_to do |format|
			if @lawyer.subscribed? # && params[:coupon].empty?
				format.html { redirect_to user_offerings_path(@lawyer, :ft => true) } # , :error => "You are subscribed already!" }
        format.json { render json: @lawyer, status: :ok }
      elsif params[:card] && @lawyer.create_stripe_card(params[:card]) # && @lawyer.apply_coupon(params[:coupon]) # && @lawyer.subscribe! l
        format.html { redirect_to user_offerings_path(@lawyer, :ft => true) } #, :notice => "Thank you for subscribing!" }
        format.json { render json: @lawyer, status: :created, location: @lawyer } 
      elsif params[:coupon].present? && @lawyer.apply_coupon(params[:coupon])
        format.html { redirect_to user_offerings_path(@lawyer, :ft => true) } #, :notice => "Thank you for subscribing! Your coupon applied!" }
        format.json { render json: @lawyer, status: :ok, location: @lawyer } 
      else
        format.html { render action: "new", :error => "Error. Something wrong." }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  rescue Stripe::CardError => exception
    redirect_to :back, :notice => exception.message
	end

	def coupon_validate
		respond_to do |format|
			if @lawyer.coupon_valid?(params[:coupon], false)
				format.html { render :nothing => true }
        format.json { render json: {:result => true, :coupon => @lawyer.stripe_get_coupon(params[:coupon])}, status: :ok }
      else
				format.html { render :nothing => true }
        format.json { render json: {:result => false, :errors => @lawyer.errors}, status: :ok }
      end
    end
	end	
	
	def subscribe_question
    check_question_owner
	  @client.create_stripe_customer! unless @client.stripe_customer_token
	end
	
	def subscribe_question_create
	  check_question_owner
    respond_to do |format|
      if params[:card] && @client.create_stripe_card(params[:card]) && @client.subscribe!(@stripe_plan.id)
        format.html { redirect_to subscribe_question_create_success_path, :notice => "Thanks, you'll get an email when a lawyer responds to you. In the mean time, you may contact one of the relevant lawyers below to start a discussion." }
        format.json { render json: @client, status: :created, location: @client } 
      else
        format.html { render action: "subscribe_question", :notice => "Error. Something wrong." }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  rescue Stripe::CardError => exception
    redirect_to :back, :notice => exception.message
	end

	private

	def check_lawyer_access
		redirect_to root_path, :status => :unauthorized unless current_user.is_lawyer?
		@lawyer = current_user
		@stripe_plan = Lawyer::get_stripe_plan
	end
	
	def check_question_owner
    @question = Question.find params[:question_id] || not_found
    redirect_to root_path, :status => :unauthorized unless @client.owner?(@question)
	end
	
  def subscribe_question_create_success_path
    path_hash = {}
    path_hash[:state] = State.name_for_url(@question.state_name)  if @question.state_name.present?
    path_hash[:practice_area] = PracticeArea.name_for_url(@question.practice_area) if @question.practice_area.present?
    filtered_path(path_hash)
  end	
  
  def check_client_access
    redirect_to root_path, :status => :unauthorized unless current_user.is_client?
    @client = current_user
    @stripe_plan = Client::get_stripe_plan '4'
    redirect_to lawyers_path, :notice => "You are subscribed already!" if @client.subscribed?(@stripe_plan.id)
  end

end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/views/stripes/_subscribe_question_form.html.haml
= raw flash[:error]
- errors = @client.errors
= form_for(@client, :url => subscribe_question_create_stripe_path, :method => :post, :html => {:id => :new_subscription}) do |f|
  = f.hidden_field :stripe_card_token
  = f.hidden_field :email
  = hidden_field_tag :stripe_plan_amount, @stripe_plan.amount.to_i
  - unless flash[:error]
    - if errors.size > 0
      .error_explanation
        %h4.error Please fix the following errors:
        %ul.errors
          - errors.full_messages.each do |error|
            %li= error   
  = f.hidden_field :email
  = hidden_field_tag :question_id, @question.id
  %table.card_user_info
    %tbody
      %tr.cards_row
        %td Credit Card
        %td.cards
          = image_tag('visa_icon.png')
          = image_tag('mc_icon.png')
          = image_tag('ae_icon.png')
          = image_tag('discover_icon.png')
      
        - if @client.stripe_card_token.present?
          %tr
            %td
            %td= label_tag :card, 'Credit card has been provided.'
        - else
          %tr
            %td{:colspan=>2}
              %table.card_info_table
                %tbody
                  %tr
                    %td.labels Credit Card #:
                    %td= text_field_tag 'card[number]', nil, :required => :required, :validate => true
                    %td.separator
                    %td.labels Expires on:
                    %td
                      = select_month nil, {add_month_numbers: true}, {name: 'card[exp_month]', id: "card_month", :required => :required, :validate => true}
                      = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: 'card[exp_year]', id: "card_year", :required => :required, :validate => true}
                  %tr
                    %td.labels CVV Code:
                    %td
                      = text_field_tag 'card[cvc]', nil, :required => :required, :validate => true
                      %a.cvv-info{:href => '#'}
                    %td.separator      
        %tr
          %td.buttons_left
          %td.buttons{:colspan=>4}
            = f.submit 'Continue', :class=>"button", id: "submit_subscribe"
            %span#siteseal
              %script{:type=>"text/javascript", :src => 'https://seal.godaddy.com/getSeal?sealID=DY6qS9Z5Yb3G0eASdQ2SOHDc5j8MndNNTbTEvYzffdVwSYY0hv2'}
      %tr.row_notice
        %td

        %td.card_notice#stripe_error
          %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser
          

app/views/stripes/_subscribtion_form.html.haml
= raw flash[:error]
- errors = @lawyer.errors
= form_for(@lawyer, :url => stripe_path, :method => :post, :html => {:id => :new_subscription}) do |f|
  = f.hidden_field :stripe_card_token
  = f.hidden_field :email
  = hidden_field_tag :stripe_plan_amount, AppParameter.lawyer_mountly_fee.to_i
  - unless flash[:error]
    - if errors.size > 0
      .error_explanation
        %h4.error Please fix the following errors:
        %ul.errors
          - errors.full_messages.each do |error|
            %li= error   
  = f.hidden_field :email
  %table.card_user_info
    %tbody
      %tr.cards_row
        %td Credit Card
        %td.cards
          = image_tag('visa_icon.png')
          = image_tag('mc_icon.png')
          = image_tag('ae_icon.png')
          = image_tag('discover_icon.png')
      
        - if @lawyer.stripe_card_token.present?
          %tr
            %td
            %td= label_tag :card, 'Credit card has been provided.'
          %tr  
            %td
            %td
              -#= text_field_tag :coupon, nil
              -#%a.gray_button#apply_coupon_button{:href => coupon_validate_stripe_path(:format => :json)} Apply 
        - else
          %tr
            %td{:colspan=>2}
              %table.card_info_table
                %tbody
                  %tr
                    %td.labels Credit Card #:
                    %td= text_field_tag 'card[number]', nil, :required => :required, :validate => true
                    %td.separator
                    %td.labels Expires on:
                    %td.expiration_col
                      = select_month nil, {add_month_numbers: true}, {name: 'card[exp_month]', id: "card_month", :required => :required, :validate => true}
                      = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: 'card[exp_year]', id: "card_year", :required => :required, :validate => true}
                  %tr
                    %td.labels CVV Code:
                    %td
                      = text_field_tag 'card[cvc]', nil, :required => :required, :validate => true
                      %a.cvv-info{:href => '#'}
                      .tooltip.big.cvv 3 digit code on the back of your card
                    %td.separator
                    %td.labels
                      Promo code:
                      %br/
                      (optional)
                    %td.promo_code
                      = text_field_tag :coupon, nil
                      %a#apply_coupon_button{:href => coupon_validate_stripe_path(:format => :json)} 
                        .gray_button
                          Apply        
      %tr
        %td.buttons_left
        %td.buttons{:colspan=>4}
          = f.submit 'Continue', :class=>"button", id: "submit_subscribe"
          %span#siteseal
            %script{:type=>"text/javascript", :src => 'https://seal.godaddy.com/getSeal?sealID=DY6qS9Z5Yb3G0eASdQ2SOHDc5j8MndNNTbTEvYzffdVwSYY0hv2'}
                
      
      %tr.row_notice
        %td

        %td.card_notice#stripe_error
          You will be charged once your bar membership is verified.
          %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser
          

app/views/stripes/new.html.haml
.lawyer_subscribtion.apply-form-wrapper#page
  %h1.form-header Lawdingo Lawyer Subscription
  %div
    .process-wrapper.activation
      .process-header
        .process-bar
        .first-step.steps 1
        .second-step.steps.active 2
        .third-step.steps 3
        .clear
        %p.first-notice.notices Create Account
        %p.second-notice.notices Activate Subcription
        %p.third-notice.notices Complete Profile
      .card-activation
        %h3 
          Activate your Lawdingo profile:   
          %span#subscription_price $#{AppParameter.lawyer_mountly_fee.to_i}/month.
          No commitment, and money back guarantee if you’re not satisfied within the first month.

        .card-info
          = render 'subscribtion_form'
    .right-wrapper
      .right-block.testimonials
        %h3 Testimonials
        .testimonials_slider
          %div
            %p Lawdingo works! I have had paying clients from Lawdingo and I haven't had to expend a lot of time, effort, or money to get them.
            %p.signature - Deepa Menon, Attorney
          %div 
            %p Wouldn’t have used or paid for a lawyer if it weren’t for Lawdingo
            %p.signature - Lawdingo client
          %div
            %p For just over $100 for a half hour call, I got the advice I needed from a top-quality lawyer on Lawdingo.
            %p.signature - Lawdingo client
        .clear
      .right-block
        %h3 Attorney Benefits
        %ul
          %li Get paid to talk to potential new clients
          %li Attorney profile featuring your practice
          %li List flat-fee services, record intro video
          %li Display availability, accept appointments
          %li Receive legal inquiries relevant to you
          %li No fee-splitting or referral fees charged
          %li Just $#{AppParameter.lawyer_mountly_fee.to_i}/month with no commitments
      .contact_outer
        %p 
          Questions? Contact:
          %a{:href => 'mailto:info@lawdingo.com'} info@lawdingo.com 
          %br/
          or 415-234-DINGO (3464).

app/views/stripes/subscribe_question.html.haml
.subscribe_question-form-wrapper#page
  %h1.form-header Get a legal question answered
  %div
    .process-wrapper.activation
      .process-header
        .process-bar
        .first-step.steps 1
        .second-step.steps.active 2
        .third-step.steps 3
        .clear
        %p.first-notice.notices Submit Legal Inquiry
        %p.second-notice.notices Pay Inquiry Fee
        %p.third-notice.notices Lawyers Respond
      .card-activation
        %h3 
          Getting a response to your legal question costs 
          %span#subscription_price $#{(@stripe_plan.amount.*0.01).to_i}.
          %br
          %span.normal
            Not happy with the quality of response you get? Email us (refunds@lawdingo.com) for a refund, no questions asked. 
  
        .card-info
          = render 'subscribe_question_form'
    